### ISSUE TITLE
Version 1.6.3 is not available

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/astunparse-feedstock#12]
Although there is a merged PR for version 1.6.3 (https://github.com/conda-forge/astunparse-feedstock/pull/9) there is no package for that version available: https://anaconda.org/conda-forge/astunparse

**Comment by h-vetinari** [comment]
Good timing, I just stumbled over this as well due to: https://github.com/conda-forge/tensorflow-feedstock/pull/110

I didn't find any records of why these packages were removed (or perhaps never built) in https://github.com/conda-forge/admin-requests nor https://github.com/conda-forge/conda-forge-repodata-patches-feedstock, so trying to rebuild in #13
